apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: restaurant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: restaurant-registry:5000/restaurant-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          env:
            # Récupération des clés publiques : URL interne au cluster
            - name: KEYCLOAK_JWKS_URI
              value: "http://keycloak-svc.security.svc.cluster.local:8080/auth/realms/restaurant/protocol/openid-connect/certs"
            # Issuer attendu dans les tokens : URL publique (vue du navigateur/curl)
            - name: KEYCLOAK_ISSUER
              value: "http://localhost:8082/auth/realms/restaurant"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: restaurant
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
